# Обучение моделей для кредитного скоринга
Итак, пришло время снова обучить модели для кредитного скоринга. Обучать мы будем две модели
1. Одна будет работать с новыми клиентами банка, о ком еще нет информации в базе данных 
2. Вторая будет работать со старыми клиентами банка, о которых информация в базе данных имеется

Разумеется, первая модель будет хуже второй за счет того, что для первой модели у нас будет меньше данных. Однако мы все равно должны 

Начнем обучение!

Содержание
1. Импорт библиотек
2. Загрузка данных
3. Обучение модели для новых клиентов
    - Предобработка данных
    - Обучение модели
    - Оценка результатов
4. Обучение модели для старых клиентов
    - Предобработка данных
    - Обучение модели
    - Оценка результатов

## 1. Импорт библиотек

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("darkgrid")

## 2. Загрузка данных

In [3]:
train_data = pd.read_csv("../data/train_dataset.csv", index_col="id")
train_data.head()

,age,education,income,has_car,car_is_foreign,has_work,has_passport,bki_score,requests_count,rejected_applications_count,region_rating,home_address_category,work_address_category,social_network_analysis_score,first_record_age,default
id,,,,,,,,,,,,,,,,
1,27,1,32000,1,1,0,0,-1.917831,0,0,40,2,3,1,4,0
2,26,2,50000,0,0,0,0,-1.153144,2,0,60,2,3,2,1,0
3,35,1,20000,0,0,1,0,-1.732810,0,0,40,1,2,4,3,0
4,35,2,80000,0,0,1,0,-2.552133,2,0,20,2,3,1,3,0
5,24,3,27000,0,0,0,0,-1.914581,1,0,50,2,3,1,2,0

In [4]:
train_features = train_data.drop(["default"], axis=1)
train_targets = train_data["default"]

## 3. Обучение модели для новых клиентов
Информации о новых клиентов нет в базе данных. Если у нас не будет доступов к базам других банков (если новый клиент является клиентом хоть какого-то банка) мы сможем воспользоваться лишь его анкетными данными.

### Предобработка данных

In [5]:
train_features.columns

Index(['age', 'education', 'income', 'has_car', 'car_is_foreign', 'has_work',
       'has_passport', 'bki_score', 'requests_count',
       'rejected_applications_count', 'region_rating', 'home_address_category',
       'work_address_category', 'social_network_analysis_score',
       'first_record_age'],
      dtype='object')

Отберем только те признаки, которые мы можем использовать в анкете

In [6]:
train_features_model_1 = train_features[[
    'age', 
    'education', 
    'income', 
    'has_car', 
    'car_is_foreign', 
    'has_work',
    'has_passport'
]]

train_features_model_1.head()

    age  education  income  has_car  car_is_foreign  has_work  has_passport
id
1    27          1   32000        1               1         0             0
2    26          2   50000        0               0         0             0
3    35          1   20000        0               0         1             0
4    35          2   80000        0               0         1             0
5    24          3   27000        0               0         0             0

In [10]:
train_features_model_1.shape, train_targets.shape

((180816, 7), (180816,))

Это максимальный приемлемый набор характеристик клиента, которые он впринципе может ввести. Признаков немного, а значит конверсия будет на высоте.

Разобьем получившуюся выборку на тренировочную, валидационную и тестовую

In [20]:
from sklearn.model_selection import train_test_split

TEST_SPLIT=.1
VALIDATION_SPLIT=.11111 # Just to have 

X_train_validation, X_test, y_train_validation, y_test = train_test_split(
    train_features_model_1, 
    train_targets, 
    test_size=TEST_SPLIT,
    random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_validation, 
    y_train_validation, 
    test_size=VALIDATION_SPLIT,
    random_state=42
)

X_train.shape, X_valid.shape, X_test.shape, y_train.shape, y_valid.shape, y_test.shape,

((144652, 7), (18082, 7), (18082, 7), (144652,), (18082,), (18082,))

### Обучение модели
В данном сценарии применим модель `CatBoost` (модель бустинга от Яндекса), которая хорошо справляется с категориальными признаками. Для оптимизации модели воспользуемся библиотекой `Optuna`

In [ ]:
from catboost import CatBoostClassifier

# Применим GridSearch
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 200, 1000),
        'depth': trial.suggest_int('depth', 4, 10),
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 1e-1),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10),
        'border_count': trial.suggest_int('border_count', 32, 255),
        'verbose': 0
    }

model_1_classifier = CatBoostClassifier(
    **params,
    loss_function='Logloss',
    cat_features=[1, 3, 4, 5, 6]   # индексы категориальных признаков
)